export const ADMIN_PASSWORD_FALLBACK = "admin123"
export const ADMIN_COOKIE_NAME = "admin_session"
export const BETA_PASSWORD = "HTS"
export const BETA_COOKIE_NAME = "beta_access"
export const SERVICENOW_URL = "https://hearst.service-now.com"
